# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/deeplearning',
                'doc_host': 'https://pmaxit.github.io',
                'git_url': 'https://github.com/pmaxit/deeplearning',
                'lib_path': 'deeplearning'},
  'syms': {'deeplearning.core': {'deeplearning.core.foo': ('core.html#foo', 'deeplearning/core.py')}}}
